Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#q = 'king "three sons" gold'
q = 'hansel witch'
_q = f'SELECT title FROM books_fts WHERE books_fts MATCH {db.quote(q)} ;'

for row in db.query(_q):
    print(row["title"])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOperationalError[0m                          Traceback (most recent call last)
[0;32m<ipython-input-3-8fa551e2f33b>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0m_q[0m [0;34m=[0m [0;34mf'SELECT title FROM books_fts WHERE books_fts MATCH {db.quote(q)} ;'[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[0;32m----> 5[0;31m [0;32mfor[0m [0mrow[0m [0;32min[0m [0mdb[0m[0;34m.[0m[0mquery[0m[0;34m([0m[0m_q[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m     [0mprint[0m[0;34m([0m[0mrow[0m[0;34m[[0m[0;34m"title"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/site-packages/sqlite_utils/db.py[0m in [0;36mquery[0;34m(self, sql, params)[0m
[1;32m    411[0m     ) -> Generator[dict, None, None]:
[1;32m    412[0m         [0;34m"Execute ``sql`` and return an iterable of dictionaries representing each row."[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 413[0;31m         [0mcursor[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0msql[0m[0;34m,[0m [0mparams[0m [0;32mor[0m [0mtuple[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    414[0m         [0mkeys[0m [0;34m=[0m [0;34m[[0m[0md[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;32mfor[0m [0md[0m [0;32min[0m [0mcursor[0m[0;34m.[0m[0mdescription[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    415[0m         [0;32mfor[0m [0mrow[0m [0;32min[0m [0mcursor[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/site-packages/sqlite_utils/db.py[0m in [0;36mexecute[0;34m(self, sql, parameters)[0m
[1;32m    423[0m             [0mself[0m[0;34m.[0m[0m_tracer[0m[0;34m([0m[0msql[0m[0;34m,[0m [0mparameters[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    424[0m         [0;32mif[0m [0mparameters[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 425[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mconn[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0msql[0m[0;34m,[0m [0mparameters[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    426[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    427[0m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mconn[0m[0;34m.[0m[0mexecute[0m[0;34m([0m[0msql[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mOperationalError[0m: no such table: books_fts
OperationalError: no such table: books_fts

